- name: Create a directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: 1001
    group: 1001
  loop:
    - "{{ app_dir }}"
    - "{{ pg_data_dir }}"

- name: Create secrets directories if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: 70
    group: 70
  loop:
    - "{{ keys_dir }}"
    - "{{ secrets_dir }}"

- name: Find Schema Registry deployment files (docker-compose)
  become: yes
  find:
    paths: "{{ app_src }}"
    hidden: yes
    use_regex: yes
    patterns: .*\.(yml|yaml)$
  delegate_to: localhost
  register: dc_files

- name: Push Postgres deployment files (docker-compose)
  copy:
    src: "{{ item.path }}"
    dest: "{{ app_dir }}"
    owner: ubuntu
    group: ubuntu
  with_items:
    - "{{ dc_files.files }}"

- name: Push Postgres configuration files
  copy:
    src: "{{ pg_config_src }}"
    dest: "{{ app_dir }}"
    owner: ubuntu
    group: ubuntu

