- name: Create a directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
  loop:
    - "{{ front_dir }}"

- name: Push front development
  copy:
    src: "{{ front_src }}/"
    dest: "{{ front_dir }}/"
    owner: ubuntu
    group: ubuntu

