- hosts: brokers

- hosts: producer
  become: yes
  vars:
    manage_lvm: true
    apps_dir: "/opt"
    data_dir: "/data"
    kafka_servers: "{{ groups['brokers']
      | map('extract', hostvars, ['ansible_default_ipv4', 'address'])
      | join(':9092,') }}:9092"
  vars_files:
    - lvm_vars.yml
    - connect_jobs_vars.yml
  roles:
    #- init
    #- mrlesmithjr.manage-lvm
    #- geerlingguy.docker
    - connect-jobs
