- hosts: postgres
  become: yes
  vars:
    manage_lvm: true
    apps_dir: "/opt"
    data_dir: "/data"
    docker_data_dir: "/data/docker"
    docker_daemon_options:
      data-root: '/data/docker'
  vars_files:
    - lvm_vars.yml
    - postgres_vars.yml
  roles:
    - init
    - mrlesmithjr.manage-lvm
    - geerlingguy.docker
    - postgres
