version: '2'

services:
  postgres:
    image: postgres:12.1-alpine
    command: >-
      postgres
      -c config_file=/etc/pg-config/postgresql.conf
      -c hba_file=/etc/pg-config/pg_hba.conf
    volumes:
      - ./pg-config:/etc/pg-config
      - ./data/postgres:/var/lib/postgresql/data/pgdata
      - ./.secrets:/run/secrets
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg-passwd
      - PGDATA=/var/lib/postgresql/data/pgdata
